[2250]
crown25="HSM1.C25"
crown40="HSM1.C40"
crown70="HSM1.C70"
crown100="HSM1.C100"
wedge25="HSM1.WEDGE25"
wedge40="HSM1.WEDGE40"
wedge70="HSM1.WEDGE70"
wedge100="HSM1.WEDGE100"
r2dt="LAST_RDT.R2DT"
fdt="HSM1.FDT"
ct="HSM1.CT_TEMP"
flt_ro1="HSM1.FLATNESS1"
flt_ro2="HSM1.FLATNESS2"
flt_ro3="HSM1.FLATNESS3"
flt_ro4="HSM1.FLATNESS4"
flt_ro5="HSM1.FLATNESS5"
thk_offset="HSM1.THK_COLDOFFSET"
thk_cold="HSM1.THK_COLD"



[1580]
thick_clg=""
crown25="HSM2.C25"
crown40="HSM2.C40"
crown70="HSM2.C70"
crown100="HSM2.C100"
wedge25="HSM2.WEDGE25"
wedge40="HSM2.WEDGE40"
wedge70="HSM2.WEDGE70"
wedge100="HSM2.WEDGE100"
r2dt="LAST_RDT.R2DT"
fdt="HSM2.FDT"
ct="HSM2.CT_TEMP"
flt_ro1="HSM2.FLATNESS1"
flt_ro2="HSM2.FLATNESS2"
flt_ro3="HSM2.FLATNESS3"
flt_ro4="HSM2.FLATNESS4"
flt_ro5="HSM2.FLATNESS5"
r2_cent_off="CENTERLINE_DEV"
thk_offset=""
thk_cold="HSM2.THK_COLD"
